 # Always Available
- hosts: localhost
 # Execute commands directly instead of over SSH
  connection: local
 # Use sudo
  become: true
  become_method: sudo
 # Tasks - what to do in this play
  tasks:
    # Ansible prints this name when running the playbook
    - name: Install nginx
    # Now declare the module to play. The module defines what to do
      apt:
        state: present # this package should be installed
        name: nginx
        cache_valid_time: 18000
      
      
